--Drops
DROP SCHEMA SELECTIONADOS;
DROP PROCEDURE [SELECTIONADOS].[MigracionDeDatos];
DROP PROCEDURE [SELECTIONADOS].[SP_Create_Rol];
DROP PROCEDURE [SELECTIONADOS].[SP_Get_Afiliado_By];
DROP PROCEDURE [SELECTIONADOS].[SP_Get_Funcionalidades];
DROP PROCEDURE [SELECTIONADOS].[SP_Get_Funcionalidades_Rol];
DROP PROCEDURE [SELECTIONADOS].[SP_Get_Roles];
DROP PROCEDURE [SELECTIONADOS].[SP_Get_Usuario];
DROP PROCEDURE [SELECTIONADOS].[SP_Get_Usuario_Rol];
DROP PROCEDURE [SELECTIONADOS].[SP_Update_Funionalidad_Por_Rol];
DROP PROCEDURE [SELECTIONADOS].[SP_Update_Rol];
DROP TABLE [SELECTIONADOS].[Afiliados];
DROP TABLE [SELECTIONADOS].[Asignacion_Rol];
DROP TABLE [SELECTIONADOS].[Compra_Bono];
DROP TABLE [SELECTIONADOS].[Consulta];
DROP TABLE [SELECTIONADOS].[Especialidad];
DROP TABLE [SELECTIONADOS].[Estado_Civil];
DROP TABLE [SELECTIONADOS].[Funcionalidades];
DROP TABLE [SELECTIONADOS].[Planes];
DROP TABLE [SELECTIONADOS].[Profesional];
DROP TABLE [SELECTIONADOS].[Profesional_Especialidad];
DROP TABLE [SELECTIONADOS].[Rol];
DROP TABLE [SELECTIONADOS].[Rol_X_Funcionalidad];
DROP TABLE [SELECTIONADOS].[Tipo_Especialidad];
DROP TABLE [SELECTIONADOS].[Turno];
DROP TABLE [SELECTIONADOS].[Usuarios];

SELECT
      ID_Afiliado, Nro_Afiliado, Nombre, Apellido, Tipo_Dni, Nro_Doc, Direccion, Telefono, Mail, Fecha_Nac, Sexo, Nro_Consultas, Afiliados.ID_Estado_Civil
    FROM
      [SELECTIONADOS].[Afiliados]
    WHERE
      (Afiliados.Nombre LIKE 'AAR' + '%') AND
      (Activo = 1)